### ISSUE TITLE
Can't run code

### ISSUE THREAD

**Issue by axel-kaliff** [irom-lab/AdaptSim#1]
Hi, I'm trying to recreate the experiment but can't run the code after following the instructions.

After creating a conda environment from the YAML file, building the forked drake code from source using cmake for use with the python bindings, but when I try to run the code, even just the installation test code 

"python3 -c 'import pydrake.all; print(pydrake.__file__)'"

I'm getting "ModuleNotFoundError: No module named 'pydrake.common._module_py'", and I've exported the correct directory to the python path. 

Running on Ubuntu 22.04.

Would greatly appreciate any help :)

**Comment by allenzren** [comment]
Hi, thanks for the interest in our work!

Our setup was done on Ubuntu 20.04, and we haven't not used 22.04. Would it be possible for you to test it on 20.04 instead? The forked Drake version is for 20.04.

**Comment by axel-kaliff** [comment]
Thanks for the reply, I'll try on Ubuntu 20.04 :)

**Comment by axel-kaliff** [comment]
I changed the ubuntu version and I can import pydrake :) 

Now however, I'm getting this error when running 'python test/test_double_pendulum_linearized.py'

I had to change some lines that imported `util.numeric` instead of `adaptsim.util.numeric` but I can't see how that caused this.

```
Traceback (most recent call last):
  File "test/test_double_pendulum_linearized.py", line 36, in <module>
    obs, reward, done, info = env.step(action=None)
  File "/home/axel/AdaptSim/adaptsim/env/double_pendulum_linearized_env.py", line 110, in step
    return self.step_continuous(K)
  File "/home/axel/AdaptSim/adaptsim/env/double_pendulum_linearized_env.py", line 121, in step_continuous
    ret = integrate.solve_ivp(
  File "/home/axel/miniconda3/envs/adaptsim/lib/python3.8/site-packages/scipy/integrate/_ivp/ivp.py", line 555, in solve_ivp
    solver = method(fun, t0, y0, tf, vectorized=vectorized, **options)
  File "/home/axel/miniconda3/envs/adaptsim/lib/python3.8/site-packages/scipy/integrate/_ivp/rk.py", line 94, in __init__
    self.f = self.fun(self.t, self.y)
  File "/home/axel/miniconda3/envs/adaptsim/lib/python3.8/site-packages/scipy/integrate/_ivp/base.py", line 138, in fun
    return self.fun_single(t, y)
  File "/home/axel/miniconda3/envs/adaptsim/lib/python3.8/site-packages/scipy/integrate/_ivp/base.py", line 20, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
  File "/home/axel/AdaptSim/adaptsim/env/double_pendulum_linearized_env.py", line 117, in system
    u = -K @ x
TypeError: bad operand type for unary -: 'NoneType'
```

**Comment by allenzren** [comment]
Ah my bad. I pushed a commit https://github.com/irom-lab/AdaptSim/commit/9cf80fb4268749fddf21c39eb861498bc7b052c3. Now the optimal K matrix will be used in this test example.

**Comment by axel-kaliff** [comment]
Great thank you!

Testing and training for the double pendulum works, but for the push and scoop task there seems to be assets missing.

`RuntimeError: /home/axel/AdaptSim/asset/franka_description/urdf/panda_arm.urdf:16: error: URI 'package://drake/manipulation/models/franka_description/meshes/visual/link0.obj' resolved to '/home/axel/drake-build/install/share/drake/manipulation/models/franka_description/meshes/visual/link0.obj' which does not exist.`

can't find the "meshes" directory in the drake fork.

**Comment by allenzren** [comment]
These meshes should show up in your drake-build folder; they are not in the Drake fork but generated when you build it. I am surprised that they are not generated under `/home/axel/drake-build/install/share/drake/manipulation/models/franka_description`. Could you take a look at `/home/axel/drake-build/install/share/drake/manipulation/models/`?

**Comment by axel-kaliff** [comment]
Sure, this is the result of 'ls' in that directory:

```allegro_hand_description 
jaco_description       
ur3e
franka_description        
realsense2_description  
wsg_50_description
iiwa_description          
tri_homecart            
ycb
```

There is no 'meshes' directory in the 'franka_description', only

```
LICENSE.TXT
README.md
urdf
```
